### ISSUE TITLE
Verified interfaces in idris 0.10

### ISSUE THREAD

**Issue by defanor** [japesinator/Idris-Bifunctors#1]
The verified interfaces (ex-classes) appear to be broken in idris 0.10-git:0cbea4a. Export is also broken by the new system, but that's easy to fix; getting the following error message after fixing it:

```
$ idris --install bifunctors.ipkg
Entering directory `./src'
./Data/Verified/Bifunctor.idr:7:1:
'public' is deprecated. Use 'public export' instead.
Type checking ./Data/Verified/Bifunctor.idr
./Data/Verified/Bifunctor.idr:10:44:
When checking type of constructor of Data.Verified.Bifunctor.VerifiedBifunctor:
When checking an application of function Data.Bifunctor.bimap:
        Type mismatch between
                p a b (Type of x)
        and
                p b b (Expected type)

        Specifically:
                Type mismatch between
                        a
                and
                        b
./Data/Verified/Bifunctor.idr:16:16:VerifiedBifunctor is not a type class
./Data/Verified/Bifunctor.idr:22:16:VerifiedBifunctor is not a type class
```

Works fine otherwise (with verified interfaces excluded).

**Comment by BartAdv** [comment]
This is caused by an `id` identifier being treated like an auto-implicit (due to the "new" implicit rules - all lowercased identifiers). 

The solution is to prefix with a namespace, and it's applied in 
https://github.com/japesinator/Idris-Bifunctors/pull/2

**Comment by defanor** [comment]
Yay.
